version: '3.8'

services:
  atrac-api:
    image: "${ATRAC_API_IMAGE:-seedstohr/atrac-api:latest}"
    platform: "${ATRAC_API_PLATFORM:-linux/amd64}"
    container_name: webminidisc-atrac-api
    profiles:
      - hq-atrac
    restart: unless-stopped

  frontend:
    build: .
    container_name: webminidisc-frontend
    ports:
      - "5080:80"
      - "5443:443"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: webminidisc-backend
    user: "1000:100"
    environment:
      - MUSIC_DIR=/music
      - DOTENV_PATH=/app/.env
      - REMOTEMD_URL=http://remotemd:11396
    volumes:
      - music_volume:/music:ro
      - ./.env:/app/.env
      - ./backend/data:/app/backend/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8001:8000"
    restart: unless-stopped
  remotemd:
  image: seedstohr/remotenetmd-docker:latest
  container_name: remotemd
  restart: unless-stopped
  privileged: true
  volumes:
    - "/dev:/dev:rw"
  ports:
    - "11396:11396" 

volumes:
  music_volume:
    driver: local
    driver_opts:
      type: "${VOLUME_TYPE:-none}"
      device: "${MUSIC_PATH:-/tmp}"
      o: "${VOLUME_OPTIONS:-bind}"
