version: '3.8'

services:
  frontend:
    build: .
    container_name: webminidisc-frontend
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: webminidisc-backend
    user: "1000:100"
    environment:
      - MUSIC_DIR=/music
      - DOTENV_PATH=/app/.env
    volumes:
      - music_volume:/music:ro
      - ./.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    ports:
      - "8001:8000"
    restart: unless-stopped

volumes:
  music_volume:
    driver: local
    driver_opts:
      type: "${VOLUME_TYPE:-none}"
      device: "${MUSIC_PATH}"
      o: "${VOLUME_OPTIONS:-bind}"
