
typedef enum atrac_codec_version_e {
    ATRAC_VERSION_3 = 3,
    ATRAC_VERSION_3PLUS = 5,
} atrac_codec_version;

typedef struct atrac_encoding_configuration_s {
    atrac_codec_version atrac_version;
    uint32_t bitrate_kbps;
    uint32_t channel_count;
    uint32_t samples_per_channel_per_frame;
    uint32_t sample_rate;
    uint32_t frame_size;
    uint32_t codec_info;
    uint32_t encode_algorithm;
    uint32_t needs_duplicated_samples;
} atrac_encoding_configuration;

#define SAMPLE_SIZE sizeof(uint16_t)

static const atrac_encoding_configuration supported_encoding_configurations[] = {
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 52,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x98,
        .codec_info = 0x2026,
        .encode_algorithm = 0,
        .needs_duplicated_samples = true,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 66,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x2030,
        .encode_algorithm = 1,
        .needs_duplicated_samples = true,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 66,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x22018,
        .encode_algorithm = 0,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 105,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x130,
        .codec_info = 0x2026,
        .encode_algorithm = 0,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3,
        .bitrate_kbps = 132,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x400,
        .sample_rate = 44100,
        .frame_size = 0x180,
        .codec_info = 0x2030,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 32,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0xc0,
        .codec_info = 0x1002417,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 48,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x118,
        .codec_info = 0x1002422,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 64,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x178,
        .codec_info = 0x100242e,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 96,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x230,
        .codec_info = 0x1002445,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 128,
        .channel_count = 1,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x2e8,
        .codec_info = 0x100245c,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 48,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x118,
        .codec_info = 0x1002822,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 64,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x178,
        .codec_info = 0x100282e,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 96,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x230,
        .codec_info = 0x1002845,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 128,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x2e8,
        .codec_info = 0x100285c,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 160,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x3a8,
        .codec_info = 0x1002874,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 192,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x460,
        .codec_info = 0x100288b,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 256,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x5d0,
        .codec_info = 0x10028b9,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 320,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x748,
        .codec_info = 0x10028e8,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
    {
        .atrac_version = ATRAC_VERSION_3PLUS,
        .bitrate_kbps = 352,
        .channel_count = 2,
        .samples_per_channel_per_frame = 0x800,
        .sample_rate = 44100,
        .frame_size = 0x800,
        .codec_info = 0x10028ff,
        .encode_algorithm = 1,
        .needs_duplicated_samples = false,
    },
};
